name: CI/CD pipeline

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  CI:
    name: Continous Integration
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Checkout Code
        uses: actions/checkout@v4 # Clona o repostório para ter acesso a pasta do projeto no servidor

      - name: 📩 Set up Node.js
        uses: actions/setup-node@v4 # Instala o node na versão 21
        with:
          node-version: '21'

      - name: 📥 Installing Dependencies
        run: npm install

      - name: 🧹 Linting
        run: npm run lint

      - name: 🧪 Testing
        run: npm run test

      - name: 🏗️ Building
        run: npm run build
  
  CD:
    name: Continuous Deploy
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v4
      - name: 📂 Install Vercel CLI
        run: npm install --global vercel@latest
      - name: 📩 Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: 🏗️ Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: 🚀 Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

   